version: '3.8'

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: resume_matcher_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/resume_matcher_db

  ml-service:
    build: ./ml-service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./ml-service:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ml-service

volumes:
  postgres_data: